import fs from "fs";
import path from "path";
import yaml from "js-yaml";
import { processOpenapiFile } from "docusaurus-plugin-openapi-docs/lib/openapi/openapi";
const SPEC_PATH = path.resolve(
  __dirname,
  "..",
  "docs/user_guide/api/BifroMQ-API.yaml"
);
const OUTPUT_PATH = path.resolve(
  __dirname,
  "..",
  "src/openapi/generatedOperations.ts"
);
const OUTPUT_JSON_PATH = path.resolve(
  __dirname,
  "..",
  "src/openapi/generatedOperations.json"
);

async function main(): Promise<void> {
  const specRaw = fs.readFileSync(SPEC_PATH, "utf8");
  const spec = yaml.load(specRaw);

  if (spec == null || typeof spec !== "object") {
    throw new Error("Failed to load OpenAPI spec from BifroMQ-API.yaml");
  }

  const [items] = await processOpenapiFile(spec as any, {}, { groupPathsBy: "tag" });
  const operations = items
    .filter((item: any) => item.type === "api")
    .map((item: any) => ({
      id: item.id,
      title: item.title,
      description: item.description,
      frontMatter: item.frontMatter,
      api: item.api,
    }));

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  const banner =
    "// Auto-generated by scripts/generate-openapi.ts. Do not edit.\n";
  const content = `${banner}export const generatedOperations = ${JSON.stringify(
    operations,
    null,
    2
  )} as const;\n`;
  fs.writeFileSync(OUTPUT_PATH, content, "utf8");
  fs.writeFileSync(
    OUTPUT_JSON_PATH,
    JSON.stringify(operations, null, 2),
    "utf8"
  );
  console.log(
    `Generated ${operations.length} operations to ${path.relative(
      process.cwd(),
      OUTPUT_PATH
    )} and ${path.relative(process.cwd(), OUTPUT_JSON_PATH)}`
  );
}

main().catch((error) => {
  console.error("Failed to generate OpenAPI operations:", error);
  process.exit(1);
});
